# Generated by Django 4.2.1 on 2023-05-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='e_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
