# Generated by Django 4.2.1 on 2023-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_events_e_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='e_img',
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
