# Generated by Django 4.2.1 on 2023-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_events_e_img_events_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image',
        ),
        migrations.AddField(
            model_name='events',
            name='e_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
